export const enum ActionType {
    SET_VALUE = 'SET_VALUE',
    REMOVE_VALUE = 'REMOVE_VALUE',
    SET_COMMAND_VALUE = 'SET_COMMAND_VALUE',
    TOGGLE_POSSIBLE_VALUE = 'TOGGLE_POSSIBLE_VALUE',
    SET_COMMAND_MODE = 'SET_COMMAND_MODE',
    GENERATE_NEW_SUDOKU = 'GENERATE_NEW_SUDOKU',
    SET_DIFFICULTY = 'SET_DIFFICULTY',
    RESTORE = 'RESTORE',
}
