export const enum ActionType {
    SET_VALUE = 'SET_VALUE',
    REMOVE_VALUE = 'REMOVE_VALUE',
    SET_COMMAND_VALUE = 'SET_COMMAND_VALUE',
    ADD_POSSIBLE_VALUE = 'ADD_POSSIBLE_VALUE',
    SET_COMMAND_MODE = 'SET_COMMAND_MODE',
}
